version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - monitoring
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
      - prometheus
      - loki
    entrypoint: ["/usr/src/app/entrypoint.sh"]

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - monitoring
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring
    volumes:
      - loki_data:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

networks:
  monitoring:

volumes:
  postgres_data:
  loki_data:
